package sharing

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
)

var reIface = regexp.MustCompile(`^[A-Za-z0-9._:-]{1,15}$`)

const generatedHeader = "# Generated by TarOS — edit in the TarOS UI; manual changes here are overwritten.\n"

// RenderGlobal is the [global]-level part: settings that must beat whatever the
// user's own [global] says, which is why it is included at the *end* of that
// section (Samba lets the last occurrence of a parameter win).
func RenderGlobal(m Model) string {
	var b strings.Builder
	b.WriteString(generatedHeader)
	// Refuse anonymous enumeration of users/shares: a share list that any
	// unauthenticated host on the network can read is information for nothing.
	b.WriteString("   restrict anonymous = 2\n")
	if m.Workgroup != "" {
		fmt.Fprintf(&b, "   workgroup = %s\n", m.Workgroup)
	}
	if len(m.Interfaces) > 0 {
		fmt.Fprintf(&b, "   bind interfaces only = yes\n   interfaces = lo %s\n", strings.Join(m.Interfaces, " "))
	}
	return b.String()
}

// RenderShares writes one section per managed share. ownerFor returns the user
// and group file operations run as (`force user` / `force group`).
func RenderShares(m Model, ownerFor func(Share) (user, group string, err error)) (string, error) {
	var b strings.Builder
	b.WriteString(generatedHeader)
	shares := append([]Share(nil), m.Shares...)
	sort.Slice(shares, func(i, j int) bool { return strings.ToLower(shares[i].Name) < strings.ToLower(shares[j].Name) })
	for _, s := range shares {
		u, g, err := ownerFor(s)
		if err != nil {
			return "", fmt.Errorf("share %q: %w", s.Name, err)
		}
		var valid, write []string
		for _, a := range normalizeAccess(s.Access) {
			valid = append(valid, a.User)
			if a.Mode == "rw" {
				write = append(write, a.User)
			}
		}
		fmt.Fprintf(&b, "\n[%s]\n", s.Name)
		fmt.Fprintf(&b, "   path = %s\n", s.Path)
		if s.Comment != "" {
			fmt.Fprintf(&b, "   comment = %s\n", s.Comment)
		}
		fmt.Fprintf(&b, "   browseable = %s\n", yn(s.Browseable))
		// Deny by default; write access is granted per account through `write list`.
		b.WriteString("   read only = yes\n   guest ok = no\n")
		fmt.Fprintf(&b, "   valid users = %s\n", strings.Join(valid, " "))
		if len(write) > 0 {
			fmt.Fprintf(&b, "   write list = %s\n", strings.Join(write, " "))
		}
		fmt.Fprintf(&b, "   force user = %s\n", u)
		if g != "" {
			fmt.Fprintf(&b, "   force group = %s\n", g)
		}
		b.WriteString("   create mask = 0664\n   directory mask = 0775\n   wide links = no\n")
	}
	return b.String(), nil
}

func yn(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

// ---- the include blocks in smb.conf -------------------------------------------

func block(dir, file string) []string {
	return []string{markBegin, "   include = " + dir + "/" + file, markEnd}
}

func isSection(line string) bool {
	t := strings.TrimSpace(line)
	return strings.HasPrefix(t, "[") && strings.HasSuffix(t, "]")
}

func isGlobal(line string) bool {
	return isSection(line) && strings.EqualFold(strings.TrimSpace(line), "[global]")
}

// HasIncludes reports whether both TarOS blocks are in conf.
func HasIncludes(conf, dir string) bool {
	return strings.Contains(conf, "include = "+dir+"/"+managedGlobalFile) && strings.Contains(conf, "include = "+dir+"/"+managedSharesFile) && strings.Contains(conf, markBegin)
}

// EnsureIncludes returns conf with TarOS's two include blocks added — the first
// at the end of [global], the second at the end of the file — and whether it
// changed anything. It only ever *adds* lines; nothing of the user's is touched.
func EnsureIncludes(conf, dir string) (string, bool) {
	if HasIncludes(conf, dir) {
		return conf, false
	}
	conf = RemoveIncludes(conf) // a half-present state gets rebuilt from scratch
	lines := strings.Split(conf, "\n")
	// Trailing newline handling: Split leaves a final "" for a newline-terminated file.
	trailingNL := len(lines) > 0 && lines[len(lines)-1] == ""
	if trailingNL {
		lines = lines[:len(lines)-1]
	}

	gi := -1
	for i, l := range lines {
		if isGlobal(l) {
			gi = i
			break
		}
	}
	var out []string
	if gi < 0 {
		out = append(out, "[global]")
		out = append(out, block(dir, managedGlobalFile)...)
		out = append(out, lines...)
	} else {
		end := len(lines)
		for i := gi + 1; i < len(lines); i++ {
			if isSection(lines[i]) {
				end = i
				break
			}
		}
		out = append(out, lines[:end]...)
		out = append(out, block(dir, managedGlobalFile)...)
		out = append(out, lines[end:]...)
	}
	out = append(out, block(dir, managedSharesFile)...)
	return strings.Join(out, "\n") + "\n", true
}

// RemoveIncludes deletes every TarOS marker block (marker, include line, marker).
func RemoveIncludes(conf string) string {
	lines := strings.Split(conf, "\n")
	var out []string
	skip := false
	for _, l := range lines {
		t := strings.TrimSpace(l)
		switch {
		case t == markBegin:
			skip = true
		case skip && t == markEnd:
			skip = false
		case !skip:
			out = append(out, l)
		}
	}
	return strings.Join(out, "\n")
}

// PointIncludesAt rewrites the include paths of TarOS's blocks so that a copy
// of smb.conf can be validated against *candidate* files without touching the
// live ones.
func PointIncludesAt(conf, dir, globalPath, sharesPath string) string {
	conf = strings.ReplaceAll(conf, "include = "+dir+"/"+managedGlobalFile, "include = "+globalPath)
	return strings.ReplaceAll(conf, "include = "+dir+"/"+managedSharesFile, "include = "+sharesPath)
}
